parser.go
parser_test.go

Fix for this issue: https://github.com/influxdata/influxdb/issues/9058
Removed p.consumeWhitespace() when parsing expression and added a test

fix space required after regex operator

---

ast.go
ast_test.go

This allows literals to be evaluated within the condition expression.
Fixes influxdata/influxdb#9290.

Reduce the results of ConditionExpr

---

ast.go
ast_test.go

Fixes influxdata/influxdb#9386.

The stddev() call always returns a float

---

ast.go
ast_test.go

This also uses the valuer for the Reduce call which was improperly done
the last time this was modified.
Related to influxdata/influxdb#9290.

Properly evaluate a boolean literal to erase the condition

---

ast.go
ast_test.go

Fixes influxdata/influxdb#9533.

Allow the time literal to be uppercase

---

ast.go
ast_test.go

This adds a CallValuer interface so it can be used to evaluate a
function call.
This allows influxql to remain agnostic about how a function call is
used and is used directly to support math function calls such as the
trigonometry functions without directly implementing the functions in
this library.

Support customizing how calls are handled in reduce and eval

---

ast.go
ast_test.go

A function has been added for evaluating the return type for a function
call. This takes the function call name and the types that are arguments
and will produce the data type or any errors that are encountered
because the types for the function are incorrect.
This also updates the type evaluator so it uses this new interface. It
has been improved so binary expressions are now evaluated using the eval
engine so the proper type is determined instead of doing it based on
which has the highest priority.
The hard-coded function calls have now been removed in favor of using
this new interface. The reason for this is to keep influxql as only the
language definition, where it just parses that the syntax is for a
function call, and avoid leaking implementation details into the
language …

Add a type mapper for function calls and allow EvalType to be customized

---

ast.go
ast_test.go

The call valuer implementations usually just care about the interface
values. They rarely if ever cared about if it was a variable reference
or a literal. This modifies the interface to reflect that and moves the
logic for how to convert an individual AST node to an interface in the
influxql package instead so the logic is the same everywhere.

Simplify the call valuer to remove the influxql.Expr references

---

ast.go

This PR updates `IsSystemName()` for `_name` and `_tagKey`. When reviewing this, also consider that the intent is to make a followup [change here](https://github.com/influxdata/influxdb/blob/master/tsdb/store.go#L1503) to call this function instead of removing all expressions where the LHS begins with `_`. This change is to address [influxdb/#9522](https://github.com/influxdata/influxdb/issues/9522).

update system names for measurements and tag keys

---

ast.go
ast_test.go

If a regular expression had a fixed repeat operator that was larger than
two, there was a good chance it would panic because the array to hold
the results was not copied into correctly.
Fixes influxdata/influxdb#10069.

Fix a panic when matching on a specific type of regular expression

---

ast.go
ast_test.go

This PR modifies `conditionExpr` to use the un-exported `reduce` function
when reducing a predicate expression.
The previous version of `conditionExpr` called `Reduce` recursively on an
expression tree. Because `Reduce strips` an expression of any enclosing
parentheses, the previous result of calling `conditionExpr` was a reduced
expression will zero nested paretheses. This transformed some expressions
into non-equivalent expressions due to operator precedence rules.
The unexported `reduce` function does not remove the enclosing parentheses
of its input expression and therefore reduces an expression to one that
is completely equivalent to the original.

preserve nested parentheses in predicate expressions

---

ast.go
ast_test.go
parser_test.go

This expression is not actually used by the parser and the parser won't
ever generate it, but this is helpful for utilities that need to
manipulate queries so they can insert bound parameters into the query
string and emit the query string.

Add a bound parameter to the AST node

---

params.go
parser.go
parser_test.go

It is now possible to bind more advanced values inside of the influxql
parser. The new syntax allows identifiers, regular expressions, and
durations to all be expressed within the AST by using `$` along with the
parameter name.
The bind parameters still take a `map[string]interface{}` as the input
and the previous types still bind to the same tokens in the scanner. In
addition to these, an object with a single key/value pair can be used as
the bind value. The key denotes the type of the parameter and the value
denotes what is intended to be substituted.
This method supports the following token types:
* `ident`, `identifier` -> `IDENT`
* `regex` -> `REGEX`
* `string` -> `STRING`
* `float`, `number` -> `NUMBER`
* `int`, `integer` -> `INTEGER`
* `duration` -> `DURATIONVAL`
This should allow …

feat: support advanced bound parameters

---

Jenkinsfile
go.mod
go.sum

This patch updates the Go version to 1.14.7 which is the last in the
1.14 line and includes recent security patches.

chore: Update go version to 1.13.15

---

ast.go
parser.go
sanitize.go
scanner.go

When used for appending strings, strings.Builder yields fewer
allocations and is generally faster than bytes.Buffer.
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkQuery_String-4             3219          2899          -9.94%
BenchmarkExprNames-4                6655          6646          -0.14%
BenchmarkEval-4                     519           522           +0.58%
BenchmarkParserParseStatement-4     6768          6083          -10.12%
BenchmarkSanitize-4                 5846          5525          -5.49%
benchmark                           old MB/s     new MB/s     speedup
BenchmarkParserParseStatement-4     6.65         7.40         1.11x
benchmark                           old allocs     new allocs     delta
BenchmarkQuery_String-4             44 …
```

refactor: Use strings.Builder

---

ast.go

The conventions followed by the struct values weren't entirely
clear without reading the parser and the specification.
This change should hopefully help in that respect.

clarify ShowTagValuesStatement comments

---

.circleci/config.yml
README.md
ast.go
parser.go
parser_test.go

To support https://github.com/influxdata/influxdb/issues/3318, we need to be able to represent wildcards and retention policies when parsing the show measurements statement.

feat: support db and rp wildcards in show measurements statement

---

.circleci/config.yml
go.mod
parser.go
parser_test.go

* chore: update to go 1.18
* chore: go fmt with 1.18
This was prompted by a fix in go 1.18.7 (and 1.19.2) to `regex/syntax`, which `influxql` imports. By updating the go version we ensure that people will use `influxql` with a new enough version that has the bug fix.
Note, `influxql` is imported by quite a few projects, so choose 1.18 instead of 1.19 since not all of those projects are updated to 1.19 yet (though, `influxql` tests pass with either 1.18 or 1.19).

chore: update to go 1.18

---

.circleci/config.yml

The recent push to master [failed](https://app.circleci.com/pipelines/github/influxdata/influxql/10/workflows/9a4166d3-8ba0-441d-b27a-8c3e8e259d5e/jobs/10) due to `circleci/golang:1.18` not existing. Indeed, `circleci/golang` are for the old, deprecated convenience images. Use `cimg/go:1.18` instead.

chore(circleci): use modern cimg/go:1.18

---

ast.go
parser.go
parser_test.go
token.go

This PR extends the `EXPLAIN` and `EXPLAIN ANALYZE` statement to support the `VERBOSE` keyword.

feat: Add `VERBOSE` option to `EXPLAIN`

---

ast.go
ast_test.go

Change NumberLiteral.String() to use necessary precision to accurately reproduce number instead of limiting to 3 decimal places. This ensures that upstream projects that stringify ASTs will generate a truly equivalent string.
closes: #65

fix: full precision string conversion for floating points

---

ast.go
parser.go
parser_test.go
token.go

Add optional write limits in the future and past to retention policies.
This will allow InfluxDB to reject writes that are within a retention
period, but outside of the write limits.  Customers desire this to stop
rogue users from writing data far in the past or future, causing 
performance and data quality issues. 
Syntax is `FUTURE LIMIT <duration> PAST LIMIT <duration>`
for 
`CREATE DATABASE WITH`
`CREATE RETENTION POLICY `
`ALTER RETENTION POLICY`
helps: https://github.com/influxdata/influxdb/issues/25424

feat: add FUTURE LIMIT and PAST LIMIT to retention policies
